version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    volumes:
      - ./data:/chroma/data
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/version"]
      interval: 10s
      timeout: 5s
      retries: 5

  content-loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./content:/app/content
    depends_on:
      chroma:
        condition: service_healthy

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHROMA_API_URL=http://chroma:8000
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chroma
